export type Word = { id: string; name: string; category: string; desc?: string; emoji?: string };

// 画像は static/img/<id>.svg。emoji があるものは scripts/fetch-images.ts が Twemoji から取得する。
// 無ければ頭文字カードで代用される。
const W = (category: string, list: [string, string, string?][]): Word[] =>
	list.map(([id, name, emoji]) => ({ id, name, category, emoji }));

export const WORDS: Word[] = [
	{ id: 'patocar', name: 'ぱとかー', category: 'のりもの', desc: 'まちを まもるよ' },
	{ id: 'fire-truck', name: 'しょうぼうしゃ', category: 'のりもの', desc: 'ひを けすよ' },
	{ id: 'ambulance', name: 'きゅうきゅうしゃ', category: 'のりもの', desc: 'びょういんへ はこぶよ' },
	{ id: 'garbage-truck', name: 'ごみしゅうしゅうしゃ', category: 'のりもの', desc: 'ごみを あつめるよ' },
	{ id: 'bus', name: 'ばす', category: 'のりもの', desc: 'みんなを のせるよ' },
	{ id: 'train', name: 'でんしゃ', category: 'のりもの', desc: 'せんろを はしるよ' },
	{ id: 'shinkansen', name: 'しんかんせん', category: 'のりもの', desc: 'とても はやいよ' },
	{ id: 'airplane', name: 'ひこうき', category: 'のりもの', desc: 'そらを とぶよ' },
	...W('のりもの', [
		['rocket', 'ろけっと', '🚀'],
		['ship', 'ふね', '🚢'],
		['bicycle', 'じてんしゃ', '🚲'],
		['helicopter', 'へりこぷたー', '🚁'],
		['truck', 'とらっく', '🚚'],
		['taxi', 'たくしー', '🚕'],
		['motorcycle', 'ばいく', '🏍️'],
		['tractor', 'とらくたー', '🚜'],
		['ufo', 'ゆーふぉー', '🛸']
	]),
	...W('どうぶつ', [
		['dog', 'いぬ', '🐶'],
		['cat', 'ねこ', '🐱'],
		['rabbit', 'うさぎ', '🐰'],
		['elephant', 'ぞう', '🐘'],
		['giraffe', 'きりん', '🦒'],
		['lion', 'らいおん', '🦁'],
		['monkey', 'さる', '🐵'],
		['bear', 'くま', '🐻'],
		['panda', 'ぱんだ', '🐼'],
		['koala', 'こあら', '🐨'],
		['frog', 'かえる', '🐸'],
		['cow', 'うし', '🐮'],
		['pig', 'ぶた', '🐷'],
		['sheep', 'ひつじ', '🐑'],
		['horse', 'うま', '🐴'],
		['chicken', 'にわとり', '🐔'],
		['penguin', 'ぺんぎん', '🐧'],
		['dolphin', 'いるか', '🐬'],
		['fish', 'さかな', '🐟'],
		['octopus', 'たこ', '🐙'],
		['turtle', 'かめ', '🐢'],
		['butterfly', 'ちょうちょ', '🦋'],
		['ladybug', 'てんとうむし', '🐞'],
		['snail', 'かたつむり', '🐌'],
		['snake', 'へび', '🐍'],
		['crocodile', 'わに', '🐊'],
		['bird', 'とり', '🐦'],
		['owl', 'ふくろう', '🦉'],
		['tiger', 'とら', '🐯'],
		['mouse', 'ねずみ', '🐭'],
		['hamster', 'はむすたー', '🐹'],
		['fox', 'きつね', '🦊'],
		['wolf', 'おおかみ', '🐺'],
		['zebra', 'しまうま', '🦓'],
		['hippo', 'かば', '🦛'],
		['whale', 'くじら', '🐳'],
		['crab', 'かに', '🦀'],
		['bee', 'はち', '🐝'],
		['ant', 'あり', '🐜'],
		['beetle', 'かぶとむし', '🪲'],
		['dinosaur', 'きょうりゅう', '🦕'],
		['duck', 'あひる', '🦆'],
		['squirrel', 'りす', '🐿️'],
		['deer', 'しか', '🦌']
	]),
	...W('くだもの', [
		['apple', 'りんご', '🍎'],
		['banana', 'ばなな', '🍌'],
		['orange', 'みかん', '🍊'],
		['grapes', 'ぶどう', '🍇'],
		['strawberry', 'いちご', '🍓'],
		['peach', 'もも', '🍑'],
		['melon', 'めろん', '🍈'],
		['watermelon', 'すいか', '🍉'],
		['cherry', 'さくらんぼ', '🍒'],
		['pear', 'なし', '🍐'],
		['pineapple', 'ぱいなっぷる', '🍍'],
		['lemon', 'れもん', '🍋'],
		['kiwi', 'きうい', '🥝'],
		['chestnut', 'くり', '🌰']
	]),
	...W('やさい', [
		['carrot', 'にんじん', '🥕'],
		['tomato', 'とまと', '🍅'],
		['cucumber', 'きゅうり', '🥒'],
		['eggplant', 'なす', '🍆'],
		['potato', 'じゃがいも', '🥔'],
		['onion', 'たまねぎ', '🧅'],
		['corn', 'とうもろこし', '🌽'],
		['pepper', 'ぴーまん', '🫑'],
		['mushroom', 'きのこ', '🍄'],
		['broccoli', 'ぶろっこりー', '🥦'],
		['sweet-potato', 'さつまいも', '🍠'],
		['garlic', 'にんにく', '🧄'],
		['pumpkin', 'かぼちゃ', '🎃']
	]),
	...W('たべもの', [
		['bread', 'ぱん', '🍞'],
		['rice-ball', 'おにぎり', '🍙'],
		['ramen', 'らーめん', '🍜'],
		['curry', 'かれー', '🍛'],
		['cake', 'けーき', '🍰'],
		['ice-cream', 'あいす', '🍦'],
		['pizza', 'ぴざ', '🍕'],
		['egg', 'たまご', '🥚'],
		['cheese', 'ちーず', '🧀'],
		['donut', 'どーなつ', '🍩'],
		['cookie', 'くっきー', '🍪'],
		['pudding', 'ぷりん', '🍮'],
		['sushi', 'すし', '🍣'],
		['hamburger', 'はんばーがー', '🍔'],
		['candy', 'あめ', '🍬'],
		['chocolate', 'ちょこれーと', '🍫'],
		['milk', 'ぎゅうにゅう', '🥛'],
		['juice', 'じゅーす', '🧃'],
		['dango', 'だんご', '🍡'],
		['bento', 'おべんとう', '🍱'],
		['pancake', 'ほっとけーき', '🥞'],
		['fried-shrimp', 'えびふらい', '🍤']
	]),
	...W('しぜん', [
		['sun', 'たいよう', '☀️'],
		['moon', 'つき', '🌙'],
		['star', 'ほし', '⭐'],
		['rainbow', 'にじ', '🌈'],
		['rain', 'あめ', '🌧️'],
		['snow', 'ゆき', '⛄'],
		['flower', 'はな', '🌸'],
		['tree', 'き', '🌳'],
		['mountain', 'やま', '⛰️'],
		['sea', 'うみ', '🌊'],
		['cloud', 'くも', '☁️'],
		['thunder', 'かみなり', '⚡'],
		['sunflower', 'ひまわり', '🌻'],
		['tulip', 'ちゅーりっぷ', '🌷'],
		['leaf', 'はっぱ', '🍃'],
		['fire', 'ひ', '🔥'],
		['earth', 'ちきゅう', '🌍']
	]),
	...W('からだ', [
		['eye', 'め', '👁️'],
		['ear', 'みみ', '👂'],
		['nose', 'はな', '👃'],
		['mouth', 'くち', '👄'],
		['hand', 'て', '✋'],
		['foot', 'あし', '🦶'],
		['tooth', 'は', '🦷'],
		['heart', 'はーと', '❤️']
	]),
	...W('みのまわり', [
		['clock', 'とけい', '⏰'],
		['umbrella', 'かさ', '☂️'],
		['hat', 'ぼうし', '🧢'],
		['shoes', 'くつ', '👟'],
		['glasses', 'めがね', '👓'],
		['bag', 'かばん', '🎒'],
		['book', 'ほん', '📖'],
		['pencil', 'えんぴつ', '✏️'],
		['scissors', 'はさみ', '✂️'],
		['chair', 'いす', '🪑'],
		['tv', 'てれび', '📺'],
		['phone', 'でんわ', '📞'],
		['key', 'かぎ', '🔑'],
		['house', 'いえ', '🏠'],
		['bed', 'べっど', '🛏️'],
		['toothbrush', 'はぶらし', '🪥'],
		['soap', 'せっけん', '🧼'],
		['cup', 'こっぷ', '🥤'],
		['spoon', 'すぷーん', '🥄'],
		['tshirt', 'しゃつ', '👕'],
		['socks', 'くつした', '🧦'],
		['bath', 'おふろ', '🛁'],
		['light', 'でんき', '💡'],
		['camera', 'かめら', '📷']
	]),
	...W('あそび', [
		['ball', 'ぼーる', '⚽'],
		['basketball', 'ばすけっと', '🏀'],
		['baseball', 'やきゅう', '⚾'],
		['piano', 'ぴあの', '🎹'],
		['guitar', 'ぎたー', '🎸'],
		['drum', 'たいこ', '🥁'],
		['balloon', 'ふうせん', '🎈'],
		['present', 'ぷれぜんと', '🎁'],
		['robot', 'ろぼっと', '🤖'],
		['teddy', 'ぬいぐるみ', '🧸'],
		['kite', 'たこあげ', '🪁'],
		['blocks', 'つみき', '🧱'],
		['puzzle', 'ぱずる', '🧩'],
		['game', 'げーむ', '🎮'],
		['crayon', 'くれよん', '🖍️'],
		['bubbles', 'しゃぼんだま', '🫧'],
		['slide', 'すべりだい', '🛝'],
		['pool', 'ぷーる', '🏊']
	])
];

export const CATEGORIES = [...new Set(WORDS.map((w) => w.category))];

export const charWord = (c: string): Word => ({ id: `char-${c}`, name: c, category: 'もじ' });

export const wordById = (id: string): Word | undefined =>
	id.startsWith('char-') ? charWord(id.slice(5)) : WORDS.find((w) => w.id === id);
