export type Word = { id: string; name: string; en: string; category: string; desc?: string; emoji?: string };

// 画像は static/img/<id>.svg。emoji があるものは scripts/fetch-images.ts が Twemoji から取得する。
// 無ければ頭文字カードで代用される。
const W = (category: string, list: [id: string, name: string, emoji: string | undefined, desc: string, en: string][]): Word[] =>
	list.map(([id, name, emoji, desc, en]) => ({ id, name, en, category, emoji, desc }));

export const WORDS: Word[] = [
	...W('のりもの', [
		['patocar', 'ぱとかー', undefined, 'まちを まもるよ', 'police car'],
		['fire-truck', 'しょうぼうしゃ', undefined, 'ひを けすよ', 'fire truck'],
		['ambulance', 'きゅうきゅうしゃ', undefined, 'びょういんへ はこぶよ', 'ambulance'],
		['garbage-truck', 'ごみしゅうしゅうしゃ', undefined, 'ごみを あつめるよ', 'garbage truck'],
		['bus', 'ばす', undefined, 'みんなを のせるよ', 'bus'],
		['train', 'でんしゃ', undefined, 'せんろを はしるよ', 'train'],
		['shinkansen', 'しんかんせん', undefined, 'とても はやいよ', 'bullet train'],
		['airplane', 'ひこうき', undefined, 'そらを とぶよ', 'airplane'],
		['rocket', 'ろけっと', '🚀', 'うちゅうへ とんでいくよ', 'rocket'],
		['ship', 'ふね', '🚢', 'うみを すすむよ', 'ship'],
		['bicycle', 'じてんしゃ', '🚲', 'ぺだるを こいで はしるよ', 'bicycle'],
		['helicopter', 'へりこぷたー', '🚁', 'ぷろぺらで とぶよ', 'helicopter'],
		['truck', 'とらっく', '🚚', 'にもつを はこぶよ', 'truck'],
		['taxi', 'たくしー', '🚕', 'いきたい ところへ つれていくよ', 'taxi'],
		['motorcycle', 'ばいく', '🏍️', 'たいや ふたつで はしるよ', 'motorcycle'],
		['tractor', 'とらくたー', '🚜', 'はたけを たがやすよ', 'tractor'],
		['ufo', 'ゆーふぉー', '🛸', 'うちゅうじんの のりもの？', 'ufo'],
		['steam-train', 'きかんしゃ', '🚂', 'しゅっしゅっぽっぽ', 'steam train'],
		['yacht', 'よっと', '⛵', 'かぜで うみを すすむよ', 'yacht']
	]),
	...W('どうぶつ', [
		['dog', 'いぬ', '🐶', 'わんわんと なくよ', 'dog'],
		['cat', 'ねこ', '🐱', 'にゃーと なくよ', 'cat'],
		['rabbit', 'うさぎ', '🐰', 'みみが ながいよ', 'rabbit'],
		['elephant', 'ぞう', '🐘', 'はなが ながいよ', 'elephant'],
		['giraffe', 'きりん', '🦒', 'くびが ながいよ', 'giraffe'],
		['lion', 'らいおん', '🦁', 'どうぶつの おうさま', 'lion'],
		['monkey', 'さる', '🐵', 'きに のぼるのが とくい', 'monkey'],
		['bear', 'くま', '🐻', 'はちみつが だいすき', 'bear'],
		['panda', 'ぱんだ', '🐼', 'ささを たべるよ', 'panda'],
		['koala', 'こあら', '🐨', 'きに つかまって ねるよ', 'koala'],
		['frog', 'かえる', '🐸', 'けろけろと なくよ', 'frog'],
		['cow', 'うし', '🐮', 'ぎゅうにゅうを くれるよ', 'cow'],
		['pig', 'ぶた', '🐷', 'ぶーぶーと なくよ', 'pig'],
		['sheep', 'ひつじ', '🐑', 'もこもこの けだよ', 'sheep'],
		['horse', 'うま', '🐴', 'はやく はしるよ', 'horse'],
		['chicken', 'にわとり', '🐔', 'こけこっこーと なくよ', 'chicken'],
		['penguin', 'ぺんぎん', '🐧', 'こおりの うえを あるくよ', 'penguin'],
		['dolphin', 'いるか', '🐬', 'じゃんぷが とくい', 'dolphin'],
		['fish', 'さかな', '🐟', 'みずの なかを およぐよ', 'fish'],
		['octopus', 'たこ', '🐙', 'あしが 8ほん あるよ', 'octopus'],
		['turtle', 'かめ', '🐢', 'こうらを せおっているよ', 'turtle'],
		['butterfly', 'ちょうちょ', '🦋', 'はなから はなへ とぶよ', 'butterfly'],
		['ladybug', 'てんとうむし', '🐞', 'あかい せなかに くろい てんてん', 'ladybug'],
		['snail', 'かたつむり', '🐌', 'ゆっくり すすむよ', 'snail'],
		['snake', 'へび', '🐍', 'にょろにょろ すすむよ', 'snake'],
		['crocodile', 'わに', '🐊', 'おおきな くちだよ', 'crocodile'],
		['bird', 'とり', '🐦', 'そらを とぶよ', 'bird'],
		['owl', 'ふくろう', '🦉', 'よるに おきているよ', 'owl'],
		['tiger', 'とら', '🐯', 'しましまの もようだよ', 'tiger'],
		['mouse', 'ねずみ', '🐭', 'ちゅうちゅうと なくよ', 'mouse'],
		['hamster', 'はむすたー', '🐹', 'ほっぺに たべものを つめるよ', 'hamster'],
		['fox', 'きつね', '🦊', 'ふさふさの しっぽだよ', 'fox'],
		['wolf', 'おおかみ', '🐺', 'とおぼえを するよ', 'wolf'],
		['zebra', 'しまうま', '🦓', 'しろと くろの しましま', 'zebra'],
		['hippo', 'かば', '🦛', 'みずの なかが すき', 'hippo'],
		['whale', 'くじら', '🐳', 'うみで いちばん おおきいよ', 'whale'],
		['crab', 'かに', '🦀', 'よこに あるくよ', 'crab'],
		['bee', 'はち', '🐝', 'はちみつを つくるよ', 'bee'],
		['ant', 'あり', '🐜', 'みんなで はたらくよ', 'ant'],
		['beetle', 'かぶとむし', '🪲', 'つのが かっこいいよ', 'beetle'],
		['dinosaur', 'きょうりゅう', '🦕', 'むかし いた おおきな いきもの', 'dinosaur'],
		['duck', 'あひる', '🦆', 'がーがーと なくよ', 'duck'],
		['squirrel', 'りす', '🐿️', 'どんぐりが だいすき', 'squirrel'],
		['deer', 'しか', '🦌', 'りっぱな つのが あるよ', 'deer'],
		['goat', 'やぎ', '🐐', 'かみを たべちゃうよ', 'goat'],
		['kangaroo', 'かんがるー', '🦘', 'おなかの ふくろに あかちゃん', 'kangaroo'],
		['shark', 'さめ', '🦈', 'するどい はが あるよ', 'shark'],
		['squid', 'いか', '🦑', 'あしが 10ぽん あるよ', 'squid'],
		['shrimp', 'えび', '🦐', 'ぴょんと はねるよ', 'shrimp'],
		['hedgehog', 'はりねずみ', '🦔', 'せなかが とげとげ', 'hedgehog']
	]),
	...W('くだもの', [
		['apple', 'りんご', '🍎', 'あかくて しゃきしゃき', 'apple'],
		['banana', 'ばなな', '🍌', 'きいろくて あまいよ', 'banana'],
		['orange', 'みかん', '🍊', 'かわを むいて たべるよ', 'orange'],
		['grapes', 'ぶどう', '🍇', 'つぶが たくさん', 'grapes'],
		['strawberry', 'いちご', '🍓', 'あかくて つぶつぶ', 'strawberry'],
		['peach', 'もも', '🍑', 'やわらかくて あまいよ', 'peach'],
		['melon', 'めろん', '🍈', 'あみめの もようだよ', 'melon'],
		['watermelon', 'すいか', '🍉', 'なつの くだもの', 'watermelon'],
		['cherry', 'さくらんぼ', '🍒', 'ふたつ ならんでいるよ', 'cherry'],
		['pear', 'なし', '🍐', 'みずみずしくて しゃりしゃり', 'pear'],
		['pineapple', 'ぱいなっぷる', '🍍', 'とげとげの かわだよ', 'pineapple'],
		['lemon', 'れもん', '🍋', 'すっぱいよ', 'lemon'],
		['kiwi', 'きうい', '🥝', 'なかは みどりいろ', 'kiwi'],
		['chestnut', 'くり', '🌰', 'いがいがの なかに あるよ', 'chestnut']
	]),
	...W('やさい', [
		['carrot', 'にんじん', '🥕', 'おれんじいろの やさい', 'carrot'],
		['tomato', 'とまと', '🍅', 'あかくて まるいよ', 'tomato'],
		['cucumber', 'きゅうり', '🥒', 'みどりで ながいよ', 'cucumber'],
		['eggplant', 'なす', '🍆', 'むらさきいろの やさい', 'eggplant'],
		['potato', 'じゃがいも', '🥔', 'つちの なかで そだつよ', 'potato'],
		['onion', 'たまねぎ', '🧅', 'きると なみだが でるよ', 'onion'],
		['corn', 'とうもろこし', '🌽', 'きいろい つぶが ならんでいるよ', 'corn'],
		['pepper', 'ぴーまん', '🫑', 'なかは からっぽ', 'pepper'],
		['mushroom', 'きのこ', '🍄', 'かさを かぶっているよ', 'mushroom'],
		['broccoli', 'ぶろっこりー', '🥦', 'ちいさな きみたい', 'broccoli'],
		['sweet-potato', 'さつまいも', '🍠', 'やくと あまいよ', 'sweet potato'],
		['garlic', 'にんにく', '🧄', 'つよい においだよ', 'garlic'],
		['pumpkin', 'かぼちゃ', '🎃', 'おおきくて おもいよ', 'pumpkin']
	]),
	...W('たべもの', [
		['bread', 'ぱん', '🍞', 'ふわふわで おいしいよ', 'bread'],
		['rice-ball', 'おにぎり', '🍙', 'ごはんを にぎったよ', 'rice ball'],
		['ramen', 'らーめん', '🍜', 'あつあつの めんだよ', 'ramen'],
		['curry', 'かれー', '🍛', 'ちょっと からいよ', 'curry'],
		['cake', 'けーき', '🍰', 'たんじょうびに たべるよ', 'cake'],
		['ice-cream', 'あいす', '🍦', 'つめたくて あまいよ', 'ice cream'],
		['pizza', 'ぴざ', '🍕', 'ちーずが とろーり', 'pizza'],
		['egg', 'たまご', '🥚', 'にわとりが うむよ', 'egg'],
		['cheese', 'ちーず', '🧀', 'ぎゅうにゅうから できるよ', 'cheese'],
		['donut', 'どーなつ', '🍩', 'まんなかに あなが あるよ', 'donut'],
		['cookie', 'くっきー', '🍪', 'さくさくの おかし', 'cookie'],
		['pudding', 'ぷりん', '🍮', 'ぷるぷるして あまいよ', 'pudding'],
		['sushi', 'すし', '🍣', 'さかなを ごはんに のせたよ', 'sushi'],
		['hamburger', 'はんばーがー', '🍔', 'ぱんに おにくを はさんだよ', 'hamburger'],
		['candy', 'あめ', '🍬', 'なめると あまいよ', 'candy'],
		['chocolate', 'ちょこれーと', '🍫', 'ちゃいろで あまいよ', 'chocolate'],
		['milk', 'ぎゅうにゅう', '🥛', 'ほねが つよくなるよ', 'milk'],
		['juice', 'じゅーす', '🧃', 'くだものの のみもの', 'juice'],
		['dango', 'だんご', '🍡', 'くしに ささっているよ', 'dango'],
		['bento', 'おべんとう', '🍱', 'はこに つめた ごはん', 'bento'],
		['pancake', 'ほっとけーき', '🥞', 'ふわふわで まるいよ', 'pancake'],
		['fried-shrimp', 'えびふらい', '🍤', 'さくさくの えびだよ', 'fried shrimp'],
		['udon', 'うどん', '🍲', 'ふとくて もちもちの めん', 'udon'],
		['gyoza', 'ぎょうざ', '🥟', 'かわで つつんで やくよ', 'gyoza'],
		['karaage', 'からあげ', '🍗', 'かりかりの とりにく', 'fried chicken'],
		['salad', 'さらだ', '🥗', 'やさいが いっぱい', 'salad'],
		['senbei', 'せんべい', '🍘', 'ぱりぱりの おかし', 'rice cracker'],
		['sandwich', 'さんどいっち', '🥪', 'ぱんに ぐを はさんだよ', 'sandwich']
	]),
	...W('しぜん', [
		['sun', 'たいよう', '☀️', 'ひるまに ひかるよ', 'sun'],
		['moon', 'つき', '🌙', 'よるに ひかるよ', 'moon'],
		['star', 'ほし', '⭐', 'よぞらで きらきら', 'star'],
		['rainbow', 'にじ', '🌈', 'あめの あとに でるよ', 'rainbow'],
		['rain', 'あめ', '🌧️', 'そらから ふってくるよ', 'rain'],
		['snow', 'ゆき', '⛄', 'しろくて つめたいよ', 'snow'],
		['flower', 'はな', '🌸', 'はるに さくよ', 'flower'],
		['tree', 'き', '🌳', 'おおきく そだつよ', 'tree'],
		['mountain', 'やま', '⛰️', 'たかくて おおきいよ', 'mountain'],
		['sea', 'うみ', '🌊', 'なみが ざぶーん', 'sea'],
		['cloud', 'くも', '☁️', 'そらに うかんでいるよ', 'cloud'],
		['thunder', 'かみなり', '⚡', 'ごろごろ ぴかっ', 'thunder'],
		['sunflower', 'ひまわり', '🌻', 'たいように むいて さくよ', 'sunflower'],
		['tulip', 'ちゅーりっぷ', '🌷', 'はるの おはな', 'tulip'],
		['leaf', 'はっぱ', '🍃', 'きに ついているよ', 'leaf'],
		['fire', 'ひ', '🔥', 'あつくて あかいよ', 'fire'],
		['earth', 'ちきゅう', '🌍', 'わたしたちの ほし', 'earth'],
		['volcano', 'かざん', '🌋', 'ひを ふく やまだよ', 'volcano'],
		['cactus', 'さぼてん', '🌵', 'とげが あるよ', 'cactus'],
		['maple', 'もみじ', '🍁', 'あきに あかくなるよ', 'maple']
	]),
	...W('からだ', [
		['eye', 'め', '👁️', 'ものを みるよ', 'eye'],
		['ear', 'みみ', '👂', 'おとを きくよ', 'ear'],
		['nose', 'はな', '👃', 'においを かぐよ', 'nose'],
		['mouth', 'くち', '👄', 'たべたり はなしたり', 'mouth'],
		['hand', 'て', '✋', 'ものを つかむよ', 'hand'],
		['foot', 'あし', '🦶', 'あるいたり はしったり', 'foot'],
		['tooth', 'は', '🦷', 'たべものを かむよ', 'tooth']
	]),
	...W('きもち', [
		['happy', 'うれしい', '😊', 'いいことが あったとき', 'happy'],
		['sad', 'かなしい', '😢', 'なみだが でそうなとき', 'sad'],
		['angry', 'おこる', '😠', 'ぷんぷん してるとき', 'angry'],
		['surprised', 'びっくり', '😲', 'おもいがけないことが あったとき', 'surprised'],
		['fun', 'たのしい', '😄', 'わくわく してるとき', 'fun'],
		['sleepy', 'ねむい', '😴', 'ねたくなったとき', 'sleepy'],
		['scared', 'こわい', '😨', 'どきどき してるとき', 'scared'],
		['laugh', 'わらう', '😆', 'おかしくて にこにこ', 'laugh'],
		['love', 'すき', '❤️', 'だいすきの きもち', 'love'],
		['yummy', 'おいしい', '😋', 'たべものが おいしいとき', 'yummy'],
		['shy', 'はずかしい', '😳', 'かおが あかくなるとき', 'shy']
	]),
	...W('みのまわり', [
		['clock', 'とけい', '⏰', 'じかんを おしえるよ', 'clock'],
		['umbrella', 'かさ', '☂️', 'あめの ひに さすよ', 'umbrella'],
		['hat', 'ぼうし', '🧢', 'あたまに かぶるよ', 'hat'],
		['shoes', 'くつ', '👟', 'あしに はくよ', 'shoes'],
		['glasses', 'めがね', '👓', 'よく みえるように なるよ', 'glasses'],
		['bag', 'かばん', '🎒', 'にもつを いれるよ', 'bag'],
		['book', 'ほん', '📖', 'おはなしが かいてあるよ', 'book'],
		['pencil', 'えんぴつ', '✏️', 'じを かくよ', 'pencil'],
		['scissors', 'はさみ', '✂️', 'かみを きるよ', 'scissors'],
		['chair', 'いす', '🪑', 'すわるよ', 'chair'],
		['tv', 'てれび', '📺', 'ばんぐみを みるよ', 'tv'],
		['phone', 'でんわ', '📞', 'もしもしと はなすよ', 'phone'],
		['key', 'かぎ', '🔑', 'どあを あけるよ', 'key'],
		['house', 'いえ', '🏠', 'かぞくと すむ ところ', 'house'],
		['bed', 'べっど', '🛏️', 'よるに ねるよ', 'bed'],
		['toothbrush', 'はぶらし', '🪥', 'はを みがくよ', 'toothbrush'],
		['soap', 'せっけん', '🧼', 'てを あらうよ', 'soap'],
		['cup', 'こっぷ', '🥤', 'のみものを いれるよ', 'cup'],
		['spoon', 'すぷーん', '🥄', 'すくって たべるよ', 'spoon'],
		['tshirt', 'しゃつ', '👕', 'からだに きるよ', 'shirt'],
		['socks', 'くつした', '🧦', 'あしに はくよ', 'socks'],
		['bath', 'おふろ', '🛁', 'からだを あらうよ', 'bath'],
		['light', 'でんき', '💡', 'へやを あかるくするよ', 'light'],
		['camera', 'かめら', '📷', 'しゃしんを とるよ', 'camera'],
		['door', 'どあ', '🚪', 'あけて はいるよ', 'door'],
		['window', 'まど', '🪟', 'そとが みえるよ', 'window'],
		['gloves', 'てぶくろ', '🧤', 'てを あたためるよ', 'gloves']
	]),
	...W('あそび', [
		['ball', 'ぼーる', '⚽', 'けったり なげたり', 'ball'],
		['basketball', 'ばすけっと', '🏀', 'ごーるに いれるよ', 'basketball'],
		['baseball', 'やきゅう', '⚾', 'ばっとで うつよ', 'baseball'],
		['piano', 'ぴあの', '🎹', 'けんばんを ひくよ', 'piano'],
		['guitar', 'ぎたー', '🎸', 'げんを はじくよ', 'guitar'],
		['drum', 'たいこ', '🥁', 'どんどん たたくよ', 'drum'],
		['balloon', 'ふうせん', '🎈', 'ふわふわ うかぶよ', 'balloon'],
		['present', 'ぷれぜんと', '🎁', 'なにが はいっているかな', 'present'],
		['robot', 'ろぼっと', '🤖', 'きかいの ともだち', 'robot'],
		['teddy', 'ぬいぐるみ', '🧸', 'ふわふわで だきしめたい', 'teddy bear'],
		['kite', 'たこあげ', '🪁', 'かぜで そらに あがるよ', 'kite'],
		['blocks', 'つみき', '🧱', 'つんで あそぶよ', 'blocks'],
		['puzzle', 'ぱずる', '🧩', 'ぴーすを あわせるよ', 'puzzle'],
		['game', 'げーむ', '🎮', 'こんとろーらーで あそぶよ', 'game'],
		['crayon', 'くれよん', '🖍️', 'えを かくよ', 'crayon'],
		['bubbles', 'しゃぼんだま', '🫧', 'ふーっと ふくと とぶよ', 'bubbles'],
		['slide', 'すべりだい', '🛝', 'しゅーっと すべるよ', 'slide'],
		['pool', 'ぷーる', '🏊', 'みずの なかで およぐよ', 'pool'],
		['ferris-wheel', 'かんらんしゃ', '🎡', 'ゆっくり まわって たかい', 'ferris wheel'],
		['yoyo', 'よーよー', '🪀', 'いとで あがったり さがったり', 'yoyo'],
		['violin', 'ばいおりん', '🎻', 'ゆみで ひくよ', 'violin']
	])
];

export const CATEGORIES = [...new Set(WORDS.map((w) => w.category))];

export const charWord = (c: string): Word => ({ id: `char-${c}`, name: c, en: c, category: 'もじ' });

export const wordById = (id: string): Word | undefined =>
	id.startsWith('char-') ? charWord(id.slice(5)) : WORDS.find((w) => w.id === id);
