export type Word = { id: string; name: string; en: string; category: string; emoji?: string };

// 画像は static/img/<id>.svg。emoji があるものは scripts/fetch-images.ts が Twemoji から取得する。
// 無ければ頭文字カードで代用される。
const W = (category: string, list: [id: string, name: string, emoji: string | undefined, en: string][]): Word[] =>
  list.map(([id, name, emoji, en]) => ({ id, name, en, category, emoji }));

export const WORDS: Word[] = [
  ...W('どうぶつ', [
    ['dog', 'いぬ', '🐶', 'dog'],
    ['cat', 'ねこ', '🐱', 'cat'],
    ['rabbit', 'うさぎ', '🐰', 'rabbit'],
    ['elephant', 'ぞう', '🐘', 'elephant'],
    ['giraffe', 'きりん', '🦒', 'giraffe'],
    ['lion', 'らいおん', '🦁', 'lion'],
    ['monkey', 'さる', '🐵', 'monkey'],
    ['bear', 'くま', '🐻', 'bear'],
    ['panda', 'ぱんだ', '🐼', 'panda'],
    ['koala', 'こあら', '🐨', 'koala'],
    ['frog', 'かえる', '🐸', 'frog'],
    ['cow', 'うし', '🐮', 'cow'],
    ['pig', 'ぶた', '🐷', 'pig'],
    ['sheep', 'ひつじ', '🐑', 'sheep'],
    ['horse', 'うま', '🐴', 'horse'],
    ['chicken', 'にわとり', '🐔', 'chicken'],
    ['penguin', 'ぺんぎん', '🐧', 'penguin'],
    ['dolphin', 'いるか', '🐬', 'dolphin'],
    ['fish', 'さかな', '🐟', 'fish'],
    ['octopus', 'たこ', '🐙', 'octopus'],
    ['turtle', 'かめ', '🐢', 'turtle'],
    ['butterfly', 'ちょうちょ', '🦋', 'butterfly'],
    ['ladybug', 'てんとうむし', '🐞', 'ladybug'],
    ['snail', 'かたつむり', '🐌', 'snail'],
    ['snake', 'へび', '🐍', 'snake'],
    ['crocodile', 'わに', '🐊', 'crocodile'],
    ['bird', 'とり', '🐦', 'bird'],
    ['owl', 'ふくろう', '🦉', 'owl'],
    ['tiger', 'とら', '🐯', 'tiger'],
    ['mouse', 'ねずみ', '🐭', 'mouse'],
    ['hamster', 'はむすたー', '🐹', 'hamster'],
    ['fox', 'きつね', '🦊', 'fox'],
    ['wolf', 'おおかみ', '🐺', 'wolf'],
    ['zebra', 'しまうま', '🦓', 'zebra'],
    ['hippo', 'かば', '🦛', 'hippo'],
    ['whale', 'くじら', '🐳', 'whale'],
    ['crab', 'かに', '🦀', 'crab'],
    ['bee', 'はち', '🐝', 'bee'],
    ['ant', 'あり', '🐜', 'ant'],
    ['beetle', 'かぶとむし', '🪲', 'beetle'],
    ['dinosaur', 'きょうりゅう', '🦕', 'dinosaur'],
    ['duck', 'あひる', '🦆', 'duck'],
    ['squirrel', 'りす', '🐿️', 'squirrel'],
    ['deer', 'しか', '🦌', 'deer'],
    ['goat', 'やぎ', '🐐', 'goat'],
    ['kangaroo', 'かんがるー', '🦘', 'kangaroo'],
    ['shark', 'さめ', '🦈', 'shark'],
    ['squid', 'いか', '🦑', 'squid'],
    ['shrimp', 'えび', '🦐', 'shrimp'],
    ['hedgehog', 'はりねずみ', '🦔', 'hedgehog']
  ]),
  ...W('しぜん', [
    ['sun', 'たいよう', '☀️', 'sun'],
    ['moon', 'つき', '🌙', 'moon'],
    ['star', 'ほし', '⭐', 'star'],
    ['rainbow', 'にじ', '🌈', 'rainbow'],
    ['rain', 'あめ', '🌧️', 'rain'],
    ['snow', 'ゆき', '⛄', 'snow'],
    ['flower', 'はな', '🌸', 'flower'],
    ['tree', 'き', '🌳', 'tree'],
    ['mountain', 'やま', '⛰️', 'mountain'],
    ['sea', 'うみ', '🌊', 'sea'],
    ['cloud', 'くも', '☁️', 'cloud'],
    ['thunder', 'かみなり', '⚡', 'thunder'],
    ['sunflower', 'ひまわり', '🌻', 'sunflower'],
    ['dandelion', 'たんぽぽ', '🌼', 'dandelion'],
    ['tulip', 'ちゅーりっぷ', '🌷', 'tulip'],
    ['leaf', 'はっぱ', '🍃', 'leaf'],
    ['fire', 'ひ', '🔥', 'fire'],
    ['earth', 'ちきゅう', '🌍', 'earth'],
    ['volcano', 'かざん', '🌋', 'volcano'],
    ['cactus', 'さぼてん', '🌵', 'cactus'],
    ['maple', 'もみじ', '🍁', 'maple']
  ]),
  ...W('くだもの', [
    ['apple', 'りんご', '🍎', 'apple'],
    ['banana', 'ばなな', '🍌', 'banana'],
    ['orange', 'みかん', '🍊', 'orange'],
    ['grapes', 'ぶどう', '🍇', 'grapes'],
    ['strawberry', 'いちご', '🍓', 'strawberry'],
    ['peach', 'もも', '🍑', 'peach'],
    ['melon', 'めろん', '🍈', 'melon'],
    ['watermelon', 'すいか', '🍉', 'watermelon'],
    ['cherry', 'さくらんぼ', '🍒', 'cherry'],
    ['pear', 'なし', '🍐', 'pear'],
    ['pineapple', 'ぱいなっぷる', '🍍', 'pineapple'],
    ['lemon', 'れもん', '🍋', 'lemon'],
    ['kiwi', 'きうい', '🥝', 'kiwi'],
    ['chestnut', 'くり', '🌰', 'chestnut']
  ]),
  ...W('みのまわり', [
    ['clock', 'とけい', '⏰', 'clock'],
    ['umbrella', 'かさ', '☂️', 'umbrella'],
    ['postbox', 'ぽすと', '📮', 'postbox'],
    ['hat', 'ぼうし', '🧢', 'hat'],
    ['shoes', 'くつ', '👟', 'shoes'],
    ['glasses', 'めがね', '👓', 'glasses'],
    ['bag', 'かばん', '🎒', 'bag'],
    ['book', 'ほん', '📖', 'book'],
    ['pencil', 'えんぴつ', '✏️', 'pencil'],
    ['scissors', 'はさみ', '✂️', 'scissors'],
    ['chair', 'いす', '🪑', 'chair'],
    ['tv', 'てれび', '📺', 'tv'],
    ['phone', 'でんわ', '📞', 'phone'],
    ['key', 'かぎ', '🔑', 'key'],
    ['house', 'いえ', '🏠', 'house'],
    ['bed', 'べっど', '🛏️', 'bed'],
    ['toothbrush', 'はぶらし', '🪥', 'toothbrush'],
    ['soap', 'せっけん', '🧼', 'soap'],
    ['cup', 'こっぷ', '🥤', 'cup'],
    ['spoon', 'すぷーん', '🥄', 'spoon'],
    ['tshirt', 'しゃつ', '👕', 'shirt'],
    ['socks', 'くつした', '🧦', 'socks'],
    ['bath', 'おふろ', '🛁', 'bath'],
    ['light', 'でんき', '💡', 'light'],
    ['camera', 'かめら', '📷', 'camera'],
    ['door', 'どあ', '🚪', 'door'],
    ['window', 'まど', '🪟', 'window'],
    ['gloves', 'てぶくろ', '🧤', 'gloves']
  ]),
  ...W('からだ', [
    ['eye', 'め', '👁️', 'eye'],
    ['ear', 'みみ', '👂', 'ear'],
    ['nose', 'はな', '👃', 'nose'],
    ['mouth', 'くち', '👄', 'mouth'],
    ['hand', 'て', '✋', 'hand'],
    ['foot', 'あし', '🦶', 'foot'],
    ['tooth', 'は', '🦷', 'tooth'],
    ['x-ray', 'れんとげん', '🩻', 'x-ray']
  ]),
  ...W('きもち', [
    ['happy', 'うれしい', '😊', 'happy'],
    ['sad', 'かなしい', '😢', 'sad'],
    ['angry', 'おこる', '😠', 'angry'],
    ['surprised', 'びっくり', '😲', 'surprised'],
    ['fun', 'たのしい', '😄', 'fun'],
    ['sleepy', 'ねむい', '😴', 'sleepy'],
    ['scared', 'こわい', '😨', 'scared'],
    ['laugh', 'わらう', '😆', 'laugh'],
    ['love', 'すき', '❤️', 'love'],
    ['yummy', 'おいしい', '😋', 'yummy'],
    ['shy', 'はずかしい', '😳', 'shy']
  ]),
  ...W('ひと', [
    ['baby', 'あかちゃん', '👶', 'baby'],
    ['teacher', 'せんせい', '🧑‍🏫', 'teacher'],
    ['doctor', 'おいしゃさん', '🧑‍⚕️', 'doctor'],
    ['police', 'おまわりさん', '👮', 'police'],
    ['firefighter', 'しょうぼうし', '🧑‍🚒', 'firefighter'],
    ['astronaut', 'うちゅうひこうし', '🧑‍🚀', 'astronaut'],
    ['ninja', 'にんじゃ', '🥷', 'ninja'],
    ['king', 'おうさま', '🤴', 'king'],
    ['queen', 'じょおう', '👸', 'queen']
  ]),
  ...W('たべもの', [
    ['bread', 'ぱん', '🍞', 'bread'],
    ['rice-ball', 'おにぎり', '🍙', 'rice ball'],
    ['french-fries', 'ぽてと', '🍟', 'french fries'],
    ['ramen', 'らーめん', '🍜', 'ramen'],
    ['curry', 'かれー', '🍛', 'curry'],
    ['cake', 'けーき', '🍰', 'cake'],
    ['ice-cream', 'あいす', '🍦', 'ice cream'],
    ['pizza', 'ぴざ', '🍕', 'pizza'],
    ['egg', 'たまご', '🥚', 'egg'],
    ['cheese', 'ちーず', '🧀', 'cheese'],
    ['donut', 'どーなつ', '🍩', 'donut'],
    ['cookie', 'くっきー', '🍪', 'cookie'],
    ['pudding', 'ぷりん', '🍮', 'pudding'],
    ['sushi', 'すし', '🍣', 'sushi'],
    ['hamburger', 'はんばーがー', '🍔', 'hamburger'],
    ['candy', 'あめ', '🍬', 'candy'],
    ['chocolate', 'ちょこれーと', '🍫', 'chocolate'],
    ['milk', 'ぎゅうにゅう', '🥛', 'milk'],
    ['juice', 'じゅーす', '🧃', 'juice'],
    ['dango', 'だんご', '🍡', 'dango'],
    ['bento', 'おべんとう', '🍱', 'bento'],
    ['pancake', 'ほっとけーき', '🥞', 'pancake'],
    ['fried-shrimp', 'えびふらい', '🍤', 'fried shrimp'],
    ['udon', 'うどん', '🍲', 'udon'],
    ['gyoza', 'ぎょうざ', '🥟', 'gyoza'],
    ['karaage', 'からあげ', '🍗', 'fried chicken'],
    ['salad', 'さらだ', '🥗', 'salad'],
    ['senbei', 'せんべい', '🍘', 'rice cracker'],
    ['sandwich', 'さんどいっち', '🥪', 'sandwich']
  ]),
  ...W('あそび', [
    ['ball', 'ぼーる', '⚽', 'ball'],
    ['basketball', 'ばすけっと', '🏀', 'basketball'],
    ['baseball', 'やきゅう', '⚾', 'baseball'],
    ['piano', 'ぴあの', '🎹', 'piano'],
    ['guitar', 'ぎたー', '🎸', 'guitar'],
    ['drum', 'たいこ', '🥁', 'drum'],
    ['balloon', 'ふうせん', '🎈', 'balloon'],
    ['present', 'ぷれぜんと', '🎁', 'present'],
    ['robot', 'ろぼっと', '🤖', 'robot'],
    ['teddy', 'ぬいぐるみ', '🧸', 'teddy bear'],
    ['kite', 'たこあげ', '🪁', 'kite'],
    ['blocks', 'つみき', '🧱', 'blocks'],
    ['puzzle', 'ぱずる', '🧩', 'puzzle'],
    ['game', 'げーむ', '🎮', 'game'],
    ['crayon', 'くれよん', '🖍️', 'crayon'],
    ['bubbles', 'しゃぼんだま', '🫧', 'bubbles'],
    ['slide', 'すべりだい', '🛝', 'slide'],
    ['pool', 'ぷーる', '🏊', 'pool'],
    ['ferris-wheel', 'かんらんしゃ', '🎡', 'ferris wheel'],
    ['yoyo', 'よーよー', '🪀', 'yoyo'],
    ['violin', 'ばいおりん', '🎻', 'violin']
  ]),
  ...W('やさい', [
    ['carrot', 'にんじん', '🥕', 'carrot'],
    ['tomato', 'とまと', '🍅', 'tomato'],
    ['cucumber', 'きゅうり', '🥒', 'cucumber'],
    ['eggplant', 'なす', '🍆', 'eggplant'],
    ['potato', 'じゃがいも', '🥔', 'potato'],
    ['onion', 'たまねぎ', '🧅', 'onion'],
    ['corn', 'とうもろこし', '🌽', 'corn'],
    ['pepper', 'ぴーまん', '🫑', 'pepper'],
    ['mushroom', 'きのこ', '🍄', 'mushroom'],
    ['broccoli', 'ぶろっこりー', '🥦', 'broccoli'],
    ['sweet-potato', 'さつまいも', '🍠', 'sweet potato'],
    ['garlic', 'にんにく', '🧄', 'garlic'],
    ['pumpkin', 'かぼちゃ', '🎃', 'pumpkin']
  ]),
  ...W('のりもの', [
    ['patocar', 'ぱとかー', undefined, 'police car'],
    ['fire-truck', 'しょうぼうしゃ', undefined, 'fire truck'],
    ['ambulance', 'きゅうきゅうしゃ', undefined, 'ambulance'],
    ['garbage-truck', 'ごみしゅうしゅうしゃ', undefined, 'garbage truck'],
    ['bus', 'ばす', undefined, 'bus'],
    ['train', 'でんしゃ', undefined, 'train'],
    ['shinkansen', 'しんかんせん', undefined, 'bullet train'],
    ['airplane', 'ひこうき', undefined, 'airplane'],
    ['rocket', 'ろけっと', '🚀', 'rocket'],
    ['ship', 'ふね', '🚢', 'ship'],
    ['bicycle', 'じてんしゃ', '🚲', 'bicycle'],
    ['helicopter', 'へりこぷたー', '🚁', 'helicopter'],
    ['truck', 'とらっく', '🚚', 'truck'],
    ['taxi', 'たくしー', '🚕', 'taxi'],
    ['motorcycle', 'ばいく', '🏍️', 'motorcycle'],
    ['tractor', 'とらくたー', '🚜', 'tractor'],
    ['ufo', 'ゆーふぉー', '🛸', 'ufo'],
    ['steam-train', 'きかんしゃ', '🚂', 'steam train'],
    ['yacht', 'よっと', '⛵', 'yacht'],
    ['sled', 'そり', '🛷', 'sled']
  ])
];

export const CATEGORIES = [...new Set(WORDS.map((w) => w.category))];

// 1 文字だけの練習は `char-<文字>` という id の擬似単語として扱う
const CHAR_PREFIX = 'char-';
export const charWordId = (c: string) => CHAR_PREFIX + c;
export const isCharWord = (w: Word) => w.id.startsWith(CHAR_PREFIX);
export const charWord = (c: string): Word => ({ id: charWordId(c), name: c, en: c, category: 'もじ' });

export const wordById = (id: string): Word | undefined =>
  id.startsWith(CHAR_PREFIX) ? charWord(id.slice(CHAR_PREFIX.length)) : WORDS.find((w) => w.id === id);
